---
- hosts: couchdemo
  remote_user: root
  sudo: yes
  vars:
    proxy_url: "http://{{ proxy_user }}:{{ proxy_password }}@{{ proxy_host }}:{{ proxy_port }}"
  roles:
    - proxy
    - common
    - erlang

